# OnePlus Ace5 Pro 内核构建工作流配置文件
# 集成了 KernelSU Next、SUSFS、性能优化和高级调度器
# 作者：ksun 工作流优化版本 (由 Manus AI 优化)
# 最后更新：2025年7月

name: ace5pro次要测试(主工作流ksun)

# 工作流触发条件：手动触发，支持多种自定义参数
on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "CPU架构分支（默认：sm8750）"
        required: true
        default: 'sm8750'
      FEIL:
        description: "设备配置文件（默认：oneplus_ace5_pro）"
        required: true
        default: 'oneplus_ace5_pro'
      ANDROID_VERSION:
        description: "目标Android版本（默认：android15）"
        required: true
        default: 'android15'
      KERNEL_VERSION:
        description: "内核版本（默认：6.6）"
        required: true
        default: '6.6'
      KERNEL_NAME:
        description: "自定义内核名称标识"
        required: true
        default: '-android15-8-g013ec21bba94-abogki383916444'
      local_version:
        description: '内核版本后缀（如-v8，默认：-4k）'
        required: false
        default: '-4k'
        type: string
      remove_default_4k:
        description: '是否删除默认的 -4k 后缀？（勾选则删除）'
        required: false
        default: false
        type: boolean
      kernel_time:
        description: '内核构建时间（UTC格式，例如 "Tue Dec 17 23:36:49 UTC 2024"）'
        required: false
        default: 'Tue Dec 17 23:36:49 UTC 2024'
        type: string

# 构建任务定义
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      TOKEN: ${{ secrets.TOKEN }}
    
    steps:
      # ========================================
      # 第一阶段：环境准备和空间优化
      # ========================================
      
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          
      - name: Configure Git
        run: |
         git config --global user.name "build"
         git config --global user.email "build@actions.com"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
         sudo apt-get update
         sudo apt-get install -y python3 git curl ccache libelf-dev

      # ========================================
      # 第二阶段：编译缓存配置
      # ========================================
      
      - name: Restore ccache
        uses: actions/cache@v4
        with:
         path: /home/runner/.ccache
         key: ${{ runner.os }}-${{ github.repository }}-v3_ksun
         restore-keys: |
          ${{ runner.os }}-${{ github.repository }}-
          ${{ runner.os }}-
          ccache-

      - name: Setup ccache environment
        run: |
         echo "CCACHE_DIR=/home/runner/.ccache" >> $GITHUB_ENV
         echo "CCACHE_MAXSIZE=8G" >> $GITHUB_ENV
         echo "CCACHE_COMPILERCHECK=%compiler% -dumpmachine; %compiler% -dumpversion" >> $GITHUB_ENV
         echo "CCACHE_NOHASHDIR=true" >> $GITHUB_ENV
         echo "CCACHE_HARDLINK=true" >> $GITHUB_ENV
         echo "CCACHE_BASEDIR=${{ github.workspace }}" >> $GITHUB_ENV
         echo "CCACHE_LOGFILE=${{ github.workspace }}/ccache.log" >> $GITHUB_ENV
         echo "/usr/lib/ccache" >> $GITHUB_PATH
         
      - name: Show ccache stats
        run: ccache -s || true

      # ========================================
      # 第三阶段：源码获取和同步
      # ========================================
      
      - name: Install repo tool
        run: |
         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
         chmod a+x ~/repo
         sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo and sync
        run: |
         mkdir kernel_workspace && cd kernel_workspace
         repo init -u https://github.com/3620603660/kernel_manifest.git -b refs/heads/oneplus/${{ github.event.inputs.CPU }} -m ${{ github.event.inputs.FEIL }}.xml --depth=1
         repo --trace sync -c -j$(nproc --all) --no-tags
         rm -f kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports in common!"
         rm -f kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports in msm-kernel!"
         
      # ========================================
      # 第四阶段：KernelSU Next集成
      # ========================================
      
      - name: Set up KernelSU Next
        run: |
          cd kernel_workspace/kernel_platform
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s next
          cd KernelSU-Next
          KSU_VERSION=$(expr $(git rev-list --count HEAD) + 10200)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          sed -i "s/DKSU_VERSION=11998/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile

      # ========================================
      # 第五阶段：SUSFS和补丁应用 (已修正)
      # ========================================
      
      - name: Set up SUSFS & apply patches
        run: |
         set -e
         cd kernel_workspace
         git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }}
         git clone --depth=1 https://github.com/SukiSU-Ultra/SukiSU_patch.git
         git clone https://${{ secrets.TOKEN }}@github.com/3620603660/boot.git
         git clone https://github.com/WildPlusKernel/kernel_patches.git
         git clone https://github.com/3620603660/GKI_KernelSU_SUSFS.git zzh_patch
         
         cd kernel_platform
         cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch ./common/
         cp ../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU-Next/
         cp ../zzh_patch/next-patch/* ./KernelSU-Next/
         cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
         cp -r ../zzh_patch/zram/lz4/* ./common/lib/lz4/
         cp -r ../zzh_patch/zram/include/linux/* ./common/include/linux/
         cp -r ../zzh_patch/zram/${{ inputs.kernel_version }}/lz4_1.10.0.patch ./common/
         
         cd ./common
         for file in "lib/lz4/lz4_compress.c" "lib/lz4/lz4_decompress.c" "lib/lz4/lz4defs.h" "lib/lz4/lz4hc_compress.c"; do
           if [ -f "$file" ]; then echo "🗑️ 正在删除：$file"; rm -f "$file"; else echo "⚠️ 文件不存在：$file"; fi
         done
         
         cd ../
         cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
         cp -r ../SukiSU_patch/other/zram/lz4k/include/linux/* ./common/include/linux || true
         cp -r ../SukiSU_patch/other/zram/lz4k/lib/* ./common/lib || true
         cp -r ../SukiSU_patch/other/zram/lz4k/crypto/* ./common/crypto || true
         cp -r ../SukiSU_patch/other/zram/lz4k_oplus ./common/lib/ || true
         cp ../boot/1.patch ./common/
         
         cd ./KernelSU-Next
         patch -p1 --forward --fuzz=3 < 10_enable_susfs_for_ksu.patch || true
         patch -p1 --fuzz=3 --forward < apk_sign.patch || true
         patch -p1 --fuzz=3 --forward < core_hook.patch || true
         patch -p1 --fuzz=3 --forward < ksud.patch || true
         patch -p1 --fuzz=3 --forward < selinux.patch || true
         patch -p1 --fuzz=3 --forward < rules.c.patch || true
         patch -p1 --fuzz=3 --forward < sucompat.c.patch || true
         patch -p1 --fuzz=3 --forward < kernel_compat.c.patch || true
         patch -p1 --fuzz=3 --forward < min_scope_syscall_hooks_v1.4.patch || true
         
         cd ../common/
         if [[ "${{ github.event.inputs.FEIL }}" == "oneplus_13" || "${{ github.event.inputs.FEIL }}" == "oneplus_ace5_pro" ]]; then
           sed -i 's/-32,12 +32,38/-32,11 +32,37/g' 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch
           sed -i '/#include <trace\/hooks\/fs.h>/d' 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch
         fi
         
         patch -p1 < 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch || true
         cp ../../kernel_patches/69_hide_stuff.patch ./
         cp ../../kernel_patches/next/scope_min_manual_hooks_v1.4.patch ./
         patch -p1 -F 3 < scope_min_manual_hooks_v1.4.patch || true
         patch -p1 -F 3 < 69_hide_stuff.patch || true
         patch -s -p1 -F 3 < 1.patch || true
         patch -p1 -F 3 --fuzz=5 < lz4_1.10.0.patch || true
         echo "✅ SUSFS 和 scope_min_manual_hooks_v1.4 patch 应用完成"
         sed -i '/^static inline int ksu_access_ok/,/^}/ s/^/\/\//' drivers/kernelsu/kernel_compat.c

         # --- 新增：将 KernelSU 正确集成到内核构建系统 ---
         echo "🚀 Integrating KernelSU into Kconfig and Makefile..."
         cd drivers
         if ! grep -q "source \"drivers/kernelsu/Kconfig\"" Kconfig; then
           sed -i '/^endmenu/i source "drivers/kernelsu/Kconfig"' Kconfig
           echo "✅ Kconfig updated."
         fi
         if ! grep -q "obj-\$(CONFIG_KERNELSU)" Makefile; then
           echo 'obj-$(CONFIG_KERNELSU) += kernelsu/' >> Makefile
           echo "✅ Makefile updated."
         fi
         echo "✅ KernelSU integration complete."

      - name: Apply lz4kd Patches
        run: |
         set -e
         cd kernel_workspace/kernel_platform/common
         PATCH_FILE=../../SukiSU_patch/other/zram/zram_patch/${{ inputs.KERNEL_VERSION }}/lz4kd.patch
         if [[ -f "$PATCH_FILE" ]]; then
           cp "$PATCH_FILE" ./lz4kd.patch
           patch -p1 -F 3 < lz4kd.patch || true
         else
           echo "❗ lz4kd patch not found for kernel version ${{ inputs.KERNEL_VERSION }}"
         fi
         
      # ========================================
      # 第六阶段：内核配置优化 (已重构)
      # ========================================
      
      - name: Adjust Kernel Configuration for Compatibility
        id: configure_kernel
        run: |
          set -e
          cd kernel_workspace/kernel_platform/common

          echo "🚀 Dynamically finding and modifying the correct defconfig file..."
          
          DEFCONFIG_FILE=""
          POSSIBLE_DEFCONFIGS=(
            "arch/arm64/configs/${{ github.event.inputs.FEIL }}_defconfig"
            "arch/arm64/configs/vendor/${{ github.event.inputs.FEIL }}_defconfig"
            "arch/arm64/configs/vendor/sm8750_defconfig"
            "arch/arm64/configs/gki_defconfig"
            "arch/arm64/configs/defconfig"
          )

          for config in "${POSSIBLE_DEFCONFIGS[@]}"; do
            if [ -f "$config" ]; then
              DEFCONFIG_FILE="$config"
              echo "✅ Found defconfig file at: $DEFCONFIG_FILE"
              break
            fi
          done

          if [ -z "$DEFCONFIG_FILE" ]; then
            echo "❌ Error: Could not find a valid defconfig file." >&2
            exit 1
          fi
          
          # 将找到的文件路径设置为输出变量
          echo "defconfig_path=$DEFCONFIG_FILE" >> $GITHUB_OUTPUT

          CONFIG_TOOL="./scripts/config --file $DEFCONFIG_FILE"

          echo "--- Applying KernelSU, Compatibility, and Performance Settings ---"
          # 启用 KernelSU 和 SUSFS
          $CONFIG_TOOL --enable CONFIG_KSU
          $CONFIG_TOOL --enable CONFIG_KSU_SUSFS
          # 禁用与 KernelSU 冲突的优化和安全选项 (关键修复)
          $CONFIG_TOOL --disable CONFIG_LTO_CLANG
          $CONFIG_TOOL --disable CONFIG_LTO_CLANG_THIN
          $CONFIG_TOOL --disable CONFIG_CFI_CLANG
          $CONFIG_TOOL --disable CONFIG_SHADOW_CALL_STACK
          
          # 应用所有其他性能和功能配置
          $CONFIG_TOOL --enable CONFIG_CRYPTO_LZ4HC
          $CONFIG_TOOL --enable CONFIG_CRYPTO_LZ4K
          $CONFIG_TOOL --enable CONFIG_CRYPTO_LZ4KD
          $CONFIG_TOOL --enable CONFIG_CRYPTO_ZSTD
          $CONFIG_TOOL --enable CONFIG_CRYPTO_LZ4
          $CONFIG_TOOL --enable CONFIG_SCHED_CORE
          $CONFIG_TOOL --enable CONFIG_SCHED_MC
          $CONFIG_TOOL --enable CONFIG_UCLAMP_TASK
          $CONFIG_TOOL --enable CONFIG_UCLAMP_MIN_TUNABLE
          $CONFIG_TOOL --enable CONFIG_UCLAMP_MAX_TUNABLE
          $CONFIG_TOOL --enable CONFIG_SCHED_HRTICK
          $CONFIG_TOOL --enable CONFIG_CPU_IDLE_GOV_LADDER
          $CONFIG_TOOL --enable CONFIG_BLK_MQ_IOSCHED_DEADLINE
          $CONFIG_TOOL --enable CONFIG_BLK_MQ_IOSCHED_BFQ
          $CONFIG_TOOL --set-str CONFIG_DEFAULT_IOSCHED "bfq"
          $CONFIG_TOOL --enable CONFIG_TCP_CONG_BBR
          $CONFIG_TOOL --enable CONFIG_NET_SCH_CAKE
          $CONFIG_TOOL --set-str CONFIG_DEFAULT_TCP_CONG "bbr"
          $CONFIG_TOOL --set-str CONFIG_DEFAULT_NET_SCH "cake"
          
          # 设置内核本地版本后缀
          LOCAL_VERSION="${{ github.event.inputs.local_version }}"
          if [[ "${{ fromJSON(github.event.inputs.remove_default_4k) }}" == "true" ]]; then
            LOCAL_VERSION=$(echo "$LOCAL_VERSION" | sed 's/-4k//')
          fi
          $CONFIG_TOOL --set-str CONFIG_LOCALVERSION "$LOCAL_VERSION"

          echo "✅ All kernel configurations have been applied to $DEFCONFIG_FILE."

      # ========================================
      # 第七阶段：内核版本和名称配置
      # ========================================
      
      - name: Add make name
        run: |
         cd kernel_workspace/kernel_platform
         sed -i '186s|echo ".*"|echo "${KERNELVERSION}${scm_version}${config_localversion}"|' common/scripts/setlocalversion
         sed -i "s/\${scm_version}/${{ github.event.inputs.KERNEL_NAME }}/g" ./common/scripts/setlocalversion
         
      # ========================================
      # 第八阶段：高级调度器集成
      # ========================================
      
      - name: 拉取并集成 sched_ext 调度器
        run: |
         cd kernel_workspace/kernel_platform/
         git clone https://github.com/3620603660/sched_ext.git
         cp -r ./sched_ext/* ./common/kernel/sched
         rm -rf ./sched_ext/.git

      - name: 拉取afdo
        run: |
          cd kernel_workspace/kernel_platform/
          git clone https://github.com/3620603660/afdo.git

      # ========================================
      # 第九阶段：构建时间戳设置
      # ========================================
      
      - name: Set build timestamp
        run: |         
         export SOURCE_DATE_EPOCH=$(date -d "${{ github.event.inputs.kernel_time }}" +%s)
         echo "SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH" >> $GITHUB_ENV
   
      # ========================================
      # 第十阶段：内核编译 (已修正)
      # ========================================
      
      - name: Build Kernel
        run: |
         export PATH="${{ github.workspace }}/kernel_workspace/kernel_platform/prebuilts/clang/host/linux-x86/clang-r510928/bin:/usr/lib/ccache:$PATH"
         export KBUILD_BUILD_TIMESTAMP="${{ github.event.inputs.kernel_time }}"
         export AFDO_PROFILE="${{ github.workspace }}/kernel_workspace/kernel_platform/afdo/kernel.afdo"
         if [ ! -f "$AFDO_PROFILE" ]; then echo "Error: AFDO profile not found at $AFDO_PROFILE"; exit 1; fi

         echo "Using KCFLAGS: -Wno-error -fauto-profile=$AFDO_PROFILE"
         export KCFLAGS="-Wno-error -fauto-profile=$AFDO_PROFILE"
         export MAKE_ARGS="LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=clang \
         RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc \
         PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole \
         LD=ld.lld HOSTLD=ld.lld O=out SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}"

         cd kernel_workspace/kernel_platform/common
         
         # 使用上一步找到的 defconfig 文件路径来生成编译目标
         DEFCONFIG_PATH="${{ steps.configure_kernel.outputs.defconfig_path }}"
         DEFCONFIG_TARGET=$(basename "$DEFCONFIG_PATH" .defconfig)
         
         echo "--- Generating final .config from $DEFCONFIG_TARGET ---"
         make -j$(nproc) $MAKE_ARGS $DEFCONFIG_TARGET

         echo "--- Verifying final .config settings ---"
         grep -E "CONFIG_KSU=|CONFIG_LTO_CLANG=" out/.config || echo "Warning: Config verification failed."

         echo "--- Starting kernel compilation ---"
         make -j$(nproc) $MAKE_ARGS all

         mkdir -p ../dist
         cp out/arch/arm64/boot/Image ../dist/

      - name: 验证内核构建时间
        run: |
         strings kernel_workspace/kernel_platform/common/out/vmlinux | grep "${{ github.event.inputs.kernel_time }}"

      # ========================================
      # 第十一阶段：打包和发布
      # ========================================
      
      - name: Prepare AnyKernel3 package
        run: |
          cd kernel_workspace/kernel_platform/dist
          git clone https://github.com/3620603660/AnyKernel3.git AnyKernel3 --depth=1
          rm -rf AnyKernel3/.git
          rm -f AnyKernel3/push.sh
          cp Image AnyKernel3/

      - name: Upload AnyKernel3 artifact
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3_oneplus_ace5pro_${{ env.KSUVER }}_ksun
          path: kernel_workspace/kernel_platform/dist/AnyKernel3/*


